#!/usr/bin/env bash

# ============================================================================
# Backup Verification Script
# ============================================================================
#
# This script verifies the integrity of backup files using SHA256 checksums.
#
# USAGE:
#   ./scripts/verify-backup.sh <backup-file>
#   ./scripts/verify-backup.sh backups/owui-backup-20250113-120000.tar.gz
#
# The script looks for a .sha256 file alongside the backup and verifies
# that the backup file's checksum matches.
#
# EXIT CODES:
#   0 - Verification successful
#   1 - Verification failed or checksum file not found
#
# ============================================================================

set -e  # Exit on error
set -u  # Exit on undefined variable

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

show_help() {
    cat << EOF
Backup Verification Script

USAGE:
  $0 <backup-file>

EXAMPLES:
  $0 backups/owui-backup-20250113-120000.tar.gz
  $0 /path/to/backup.tar.gz.gpg

DESCRIPTION:
  Verifies backup integrity using SHA256 checksums.
  Looks for a .sha256 file alongside the backup.

OPTIONS:
  --help    Show this help message

EXIT CODES:
  0 - Verification successful
  1 - Verification failed or error
EOF
}

# ============================================================================
# Parse Arguments
# ============================================================================

if [[ $# -eq 0 ]] || [[ "$1" == "--help" ]]; then
    show_help
    exit 0
fi

BACKUP_FILE="$1"

# ============================================================================
# Validation
# ============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
log_info "Backup Integrity Verification"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if backup file exists
if [[ ! -f "$BACKUP_FILE" ]]; then
    log_error "Backup file not found: $BACKUP_FILE"
    exit 1
fi

log_success "Backup file found: $BACKUP_FILE"

# Check if checksum file exists
CHECKSUM_FILE="${BACKUP_FILE}.sha256"
if [[ ! -f "$CHECKSUM_FILE" ]]; then
    log_error "Checksum file not found: $CHECKSUM_FILE"
    echo ""
    echo "Checksum files are automatically generated by the backup script."
    echo "If this is an old backup, you may need to regenerate it."
    echo ""
    exit 1
fi

log_success "Checksum file found: $CHECKSUM_FILE"
echo ""

# ============================================================================
# Verify Checksum
# ============================================================================

log_info "Verifying checksum..."
echo ""

# Change to the directory containing the backup
cd "$(dirname "$BACKUP_FILE")"
BACKUP_FILENAME="$(basename "$BACKUP_FILE")"

# Verify checksum
if command -v sha256sum &> /dev/null; then
    # Linux
    if sha256sum -c "$(basename "$CHECKSUM_FILE")" 2>&1; then
        VERIFY_RESULT=$?
    else
        VERIFY_RESULT=1
    fi
elif command -v shasum &> /dev/null; then
    # macOS
    if shasum -a 256 -c "$(basename "$CHECKSUM_FILE")" 2>&1; then
        VERIFY_RESULT=$?
    else
        VERIFY_RESULT=1
    fi
else
    log_error "Neither sha256sum nor shasum found"
    echo "Install coreutils (Linux) or use built-in shasum (macOS)"
    exit 1
fi

echo ""

# ============================================================================
# Results
# ============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [[ $VERIFY_RESULT -eq 0 ]]; then
    log_success "✓ Backup integrity verified successfully!"
    echo ""
    echo "The backup file is intact and has not been corrupted."
    echo ""

    # Show file details
    BACKUP_SIZE=$(stat -f%z "$BACKUP_FILENAME" 2>/dev/null || stat -c%s "$BACKUP_FILENAME" 2>/dev/null)
    if command -v numfmt &> /dev/null; then
        BACKUP_SIZE_HUMAN=$(numfmt --to=iec-i --suffix=B "$BACKUP_SIZE")
    else
        BACKUP_SIZE_HUMAN="${BACKUP_SIZE} bytes"
    fi

    echo "📦 File Details:"
    echo "   File: $BACKUP_FILENAME"
    echo "   Size: $BACKUP_SIZE_HUMAN"
    echo ""

    exit 0
else
    log_error "✗ Backup integrity verification FAILED!"
    echo ""
    echo "⚠️  WARNING: The backup file may be corrupted or tampered with."
    echo ""
    echo "Possible causes:"
    echo "  • File was corrupted during transfer"
    echo "  • Disk errors or bad sectors"
    echo "  • File was modified after backup"
    echo "  • Incomplete download"
    echo ""
    echo "Recommended actions:"
    echo "  • Do NOT use this backup for restoration"
    echo "  • Create a new backup from the original source"
    echo "  • Check disk health: sudo smartctl -a /dev/sdX"
    echo ""

    exit 1
fi
